services:
  fitness:
    build: .
    container_name: fitness
    restart: always
    ports:
      - "127.0.0.1:9081:8080"
    environment:
      - AI_HOST=172.18.0.1
    volumes:
      - ./fitness.db:/app/fitness.db
      - ./.secret:/app/.secret
